[platformio]
default_envs = phev_remote_c6

[env:phev_remote_c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
extra_scripts =
    pre:tools/privacy_build.py
    pre:tools/tcp_debug_build.py
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 8MB
board_build.flash_size = 8MB
board_build.partitions = zigbee_8MB.csv
build_flags =
    -DPHEV_RAW_TCP_TEST=0
    -DPHEV_PROTOCOL_WATCH_TEST=0
    -DPHEV_WIFI_LEGACY_BGN=1
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
